# Define an array of symbolic link sources and targets
$(pwd)/zsh/zshrc:$HOME/.zshrc
$(pwd)/zsh/zshenv:$HOME/.zshenv
$(pwd)/zsh/config/config.zsh:$HOME/.config/zsh/config.zsh
$(pwd)/zsh/config/aliases.zsh:$HOME/.config/zsh/aliases.zsh
$(pwd)/zsh/config/functions.zsh:$HOME/.config/zsh/functions.zsh
$(pwd)/zsh/config/colors.zsh:$HOME/.config/zsh/colors.zsh

$(pwd)/starship:$HOME/.config/starship

$(pwd)/tmux/tmux.conf:$HOME/.tmux.conf

$(pwd)/lazygit/config.yml:$HOME/.config/lazygit/config.yml