tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# cask "xcodes"
# cask "jordanbaird-ice"
# cask "fork"
cask "ghostty"
brew "mas"

# Simple, fast and user-friendly alternative to find
brew "fd"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Command-line fuzzy finder written in Go
brew "fzf"
# Terminal multiplexer
brew "tmux"
# Plugin manager for tmux
brew "tpm"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Cross-shell prompt for astronauts
brew "starship"
# Modern, maintained replacement for ls
brew "eza"
# A better cd command
brew "zoxide"
# Simple terminal UI for git commands
brew "lazygit"
# Developer targeted fonts with a high number of glyphs
cask "font-jetbrains-mono-nerd-font"
# Keyboard customizer
cask "karabiner-elements"
# Open-source code editor
cask "visual-studio-code"

brew "yazi"
brew "ffmpeg"
brew "sevenzip"
brew "jq"
brew "poppler"
brew "ripgrep"
brew "imagemagick"

# Ambitious Vim-fork focused on extensibility and agility
# brew "neovim"

# Programmatically correct mistyped console commands
# brew "thefuck"
# Library for command-line editing
# brew "readline"
# Official Amazon AWS command-line interface
# brew "awscli"
# Cross-platform make
# brew "cmake"
# GNU compiler collection
# brew "gcc"
# Platform built on V8 to build network applications
# brew "node"
# Python version management
# brew "pyenv"
# Search tool like grep and The Silver Searcher
# brew "ripgrep"
# Powerful, clean, object-oriented scripting language
# brew "ruby"
# General-purpose lossless data-compression library
# brew "zlib"
# Cryptography and SSL/TLS Toolkit
# brew "openssl@3", link: false
# Object-relational database system
# brew "postgresql@14"
# Command-line interface for SQLite
# brew "sqlite"
# PDF rendering library (based on the xpdf-3.0 code base)
# brew "poppler"
# Universal database tool and SQL client
# cask "dbeaver-community"
# App to build and share containerized applications and microservices
# cask "docker"
# Developer targeted fonts with a high number of glyphs
# cask "font-hack-nerd-font"
# Developer targeted fonts with a high number of glyphs
# cask "font-symbols-only-nerd-font"
# Grammarly for desktop
# cask "grammarly-desktop"
# Knowledge base that works on top of a local folder of plain text Markdown files
# cask "obsidian"
# Music streaming service
# cask "spotify"
# Multimedia player
# cask "vlc"
# App that enables mouse-free UI interaction
# cask "shortcat"