# zsh Options
setopt HIST_IGNORE_ALL_DUPS

# Custom zsh
[ -f "$HOME/.config/zsh/config.zsh" ] && source "$HOME/.config/zsh/config.zsh"

# Aliases
[ -f "$HOME/.config/zsh/aliases.zsh" ] && source "$HOME/.config/zsh/aliases.zsh"

# Functions
[ -f "$HOME/.config/zsh/functions.zsh" ] && source "$HOME/.config/zsh/functions.zsh"

# Colors
[ -f "$HOME/.config/zsh/colors.zsh" ] && source "$HOME/.config/zsh/colors.zsh"

[ -f "/opt/homebrew/bin/brew" ] && export PATH="/opt/homebrew/bin:$PATH"
